### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by nataquinones** [ThomasDOtto/ratt#11]
I was trying to run `ratt` as specified in [this documentation](https://ratt.sourceforge.net/documentation.html): 

```
 ratt <Directory with embl-files> <Query-fasta sequence> <Resultname> <Transfer type> <optional: reference (multi) Fasta>
```
but that causes the following error:
```
A required option was not passed. See ratt(1) for usage information.
```
In this version, you need to specify the options `-p` for `<Resultname>` and `-t` for `<Transfer type>`. It successfully runs like this:
```
ratt <Directory with embl-files> <Query-fasta sequence> -p <Resultname> -t <Transfer type>
```

**Comment by 0xaf1f** [comment]
Yeah, consistent documentation would be nice. The current version's usage is described at https://github.com/ThomasDOtto/ratt/blob/master/ratt.1.md

**Comment by haessar** [comment]
Closing with https://github.com/ThomasDOtto/ratt/commit/2edce3351951c21e46f2765e77b6b9285937714f 
Please reopen if you feel documentation still isn't an accurate reflection
