### ISSUE TITLE
helping with maintenance vs. forking RATT

### ISSUE THREAD

**Issue by 0xaf1f** [ThomasDOtto/ratt#13]
Hi, @ThomasDOtto 
I've incorporated RATT into my annotation pipeline [Hybran](https://lpcdrp.gitlab.io/hybran/) (preprint at https://doi.org/10.1101/2022.11.09.515824), so it's in my interest to fix some issues in RATT that come up.

Would you consider making me a collaborator on this repository, or otherwise have time to accept some contributions, or should I just fork the project, call it something else, and develop it further from there? I think the concept of this tool is quite underrated and still very relevant.

thanks
Afif

**Comment by haessar** [comment]
Hi Afif. I don't believe Thomas is monitoring this repo anymore, but will speak to him about resuming maintenance shortly. We are actively using RATT also in our annotation pipeline Companion.

**Comment by haessar** [comment]
I will be actively continuing maintenance here

**Comment by 0xaf1f** [comment]
That's great news, @haessar!
