### ISSUE TITLE
> start shell script

### ISSUE THREAD

**Issue by haessar** [ThomasDOtto/ratt#16]
> start shell script

This is the old name of what is now the `ratt` executable. I compared the two and most of the differences between them are whitespace, but it looks like your version wasn't based on T. Otto's latest since it excludes the Pacbio parameter set from https://github.com/ThomasDOtto/ratt/commit/e8efc9d76fe8a998287116a52ad7142c7daec05e

_Originally posted by @0xaf1f in https://github.com/ThomasDOtto/ratt/pull/14#issuecomment-1538770122_

**Comment by 0xaf1f** [comment]
I think it'd be good to bring back the printing of usage from the command. When I originally submitted my contribution, I removed that and directed the caller to the documentation, but that was a bad call.

**Comment by 0xaf1f** [comment]
I'll prepare a PR
