### ISSUE TITLE
RATT fails to write the translation for genes whose names contain spaces

### ISSUE THREAD

**Issue by jean-baka** [ThomasDOtto/ratt#7]
Because of a restrictive parsing in `addTranslation()` in `main.ratt.pl`, RATT fails to output the translation for genes whose names contain spaces. It may not be an orthodox thing to have gene names with spaces, but in some non-model species, people do what they fancy ;) so I don't see the need to put a restriction there.

I'll suggest a patch in a minute.

**Comment by haessar** [comment]
Closing with #8
